### ISSUE TITLE
pacman hangs on Windows for ARM

### ISSUE THREAD

**Issue by phraemer** [msys2/msys2.github.io#341] opened 2024-08-18 04:56 UTC
Parallels on macOS running Windows for ARM64

Edition	Windows 11 Pro
Version	23H2
OS build	22631.4037
Experience	Windows Feature Experience Pack 1000.22700.1027.0

Following the instructions here:
https://www.msys2.org/wiki/arm64/

When I try `pacman --debug -S mingw-w64-clang-aarch64-clang` I can see I get the following output and pacman fails to exit after `debug: validity: full; reason: Success`

First in command prompt:
```
C:\Users\james>cd \msys64

C:\msys64>clangarm64.exe
```

Then:

```
james@winbox CLANGARM64 ~
$ pacman -Suy
:: Synchronizing package databases...
 clangarm64                      415.7 KiB   467 KiB/s 00:01 [###############################] 100%
 mingw32                         214.1 KiB   167 KiB/s 00:01 [###############################] 100%
 mingw64                         443.9 KiB   418 KiB/s 00:01 [###############################] 100%
 ucrt64                          470.6 KiB   558 KiB/s 00:01 [###############################] 100%
 clang32                         199.1 KiB   245 KiB/s 00:01 [###############################] 100%
 clang64                         455.8 KiB   810 KiB/s 00:01 [###############################] 100%
 msys                            268.0 KiB  2.78 MiB/s 00:00 [###############################] 100%
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (3) curl-8.9.1-1  libcurl-8.9.1-1  libgnutls-3.8.7-1

Total Download Size:   2.45 MiB
Total Installed Size:  4.49 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 curl-8.9.1-1-x86_64             798.4 KiB  3.56 MiB/s 00:00 [###############################] 100%
 libcurl-8.9.1-1-x86_64          299.2 KiB  1065 KiB/s 00:00 [###############################] 100%
 libgnutls-3.8.7-1-x86_64       1410.9 KiB  2.01 MiB/s 00:01 [###############################] 100%
 Total (3/3)                       2.4 MiB  3.27 MiB/s 00:01 [###############################] 100%
(3/3) checking keys in keyring                               [###############################] 100%
(3/3) checking package integrity                             [###############################] 100%
(3/3) loading package files                                  [###############################] 100%
(3/3) checking for file conflicts                            [###############################] 100%
(3/3) checking available disk space                          [###############################] 100%
:: Processing package changes...
(1/3) upgrading libcurl                                      [###############################] 100%
(2/3) upgrading curl                                         [###############################] 100%
(3/3) upgrading libgnutls                                    [###############################] 100%
:: Running post-transaction hooks...
(1/1) Updating the info directory file...

james@winbox CLANGARM64 ~
$ pacman --debug -S mingw-w64-clang-aarch64-clang
debug: pacman v6.1.0 - libalpm v14.0.0
debug: config: new section 'options'
debug: config: HoldPkg: pacman
debug: config: Architecture: auto
debug: config: arch: x86_64
debug: config: SigLevel: Required
debug: config: LocalFileSigLevel: Optional
debug: config: new section 'clangarm64'
debug: config file /etc/pacman.conf, line 74: including /etc/pacman.d/mirrorlist.mingw
debug: config: new section 'mingw32'
debug: config file /etc/pacman.conf, line 77: including /etc/pacman.d/mirrorlist.mingw
debug: config: new section 'mingw64'
debug: config file /etc/pacman.conf, line 80: including /etc/pacman.d/mirrorlist.mingw
debug: config: new section 'ucrt64'
debug: config file /etc/pacman.conf, line 83: including /etc/pacman.d/mirrorlist.mingw
debug: config: new section 'clang32'
debug: config file /etc/pacman.conf, line 86: including /etc/pacman.d/mirrorlist.mingw
debug: config: new section 'clang64'
debug: config file /etc/pacman.conf, line 89: including /etc/pacman.d/mirrorlist.mingw
debug: config: new section 'msys'
debug: config file /etc/pacman.conf, line 92: including /etc/pacman.d/mirrorlist.msys
debug: config: finished parsing /etc/pacman.conf
debug: setup_libalpm called
debug: option 'logfile' = /var/log/pacman.log
debug: option 'gpgdir' = /etc/pacman.d/gnupg/
debug: option 'hookdir' = /etc/pacman.d/hooks/
debug: option 'cachedir' = /var/cache/pacman/pkg/
debug: registering sync database 'clangarm64'
debug: database path for tree clangarm64 set to /var/lib/pacman/sync/clangarm64.db
debug: GPGME version: 1.23.2
debug: GPGME engine info: file=/usr/bin/gpg, home=/etc/pacman.d/gnupg/
debug: checking signature for /var/lib/pacman/sync/clangarm64.db
debug: 1 signatures returned
debug: fingerprint: 5F944B027F7FE2091985AA2EFA11531AA0AA7F57
debug: summary: valid
debug: summary: green
debug: status: Success
debug: timestamp: 1723924104
debug: exp_timestamp: 0
debug: validity: full; reason: Success
debug: key: 5F944B027F7FE2091985AA2EFA11531AA0AA7F57, Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>, owner_trust unknown, disabled 0
debug: signature is valid
debug: signature is fully trusted
debug: setting usage of 15 for clangarm64 repository
debug: adding new server URL to database 'clangarm64': https://mirror.msys2.org/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://repo.msys2.org/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirror.umd.edu/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirror.yandex.ru/mirrors/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://download.nus.edu.sg/mirror/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirror.accum.se/mirror/msys2.org/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://ftp.nluug.nl/pub/os/windows/msys2/builds/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://ftp.osuosl.org/pub/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirror.internet.asn.au/pub/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirror.selfnet.de/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirrors.dotsrc.org/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirrors.bfsu.edu.cn/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirrors.ustc.edu.cn/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirror.nju.edu.cn/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://repo.extreme-ix.org/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirror.clarkson.edu/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://quantum-mirror.hu/mirrors/pub/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirror.archlinux.tw/MSYS2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://fastmirror.pp.ua/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://ftp.cc.uoc.gr/mirrors/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirror.jmu.edu/pub/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirrors.piconets.webwerks.in/msys2-mirror/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://www2.futureware.at/~nickoe/msys2-mirror/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirrors.bit.edu.cn/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirrors.aliyun.com/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirror.iscas.ac.cn/msys2/mingw/clangarm64
debug: adding new server URL to database 'clangarm64': https://mirrors.cloud.tencent.com/msys2/mingw/clangarm64
debug: registering sync database 'mingw32'
debug: database path for tree mingw32 set to /var/lib/pacman/sync/mingw32.db
debug: checking signature for /var/lib/pacman/sync/mingw32.db
debug: 1 signatures returned
debug: fingerprint: 5F944B027F7FE2091985AA2EFA11531AA0AA7F57
debug: summary: valid
debug: summary: green
debug: status: Success
debug: timestamp: 1723924000
debug: exp_timestamp: 0
debug: validity: full; reason: Success
debug: key: 5F944B027F7FE2091985AA2EFA11531AA0AA7F57, Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>, owner_trust unknown, disabled 0
debug: signature is valid
debug: signature is fully trusted
debug: setting usage of 15 for mingw32 repository
debug: adding new server URL to database 'mingw32': https://mirror.msys2.org/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://repo.msys2.org/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirror.umd.edu/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirror.yandex.ru/mirrors/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://download.nus.edu.sg/mirror/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirror.accum.se/mirror/msys2.org/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://ftp.nluug.nl/pub/os/windows/msys2/builds/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://ftp.osuosl.org/pub/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirror.internet.asn.au/pub/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirror.selfnet.de/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirrors.dotsrc.org/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirrors.bfsu.edu.cn/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirrors.ustc.edu.cn/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirror.nju.edu.cn/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://repo.extreme-ix.org/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirror.clarkson.edu/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://quantum-mirror.hu/mirrors/pub/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirror.archlinux.tw/MSYS2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://fastmirror.pp.ua/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://ftp.cc.uoc.gr/mirrors/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirror.jmu.edu/pub/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirrors.piconets.webwerks.in/msys2-mirror/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://www2.futureware.at/~nickoe/msys2-mirror/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirrors.bit.edu.cn/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirrors.aliyun.com/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirror.iscas.ac.cn/msys2/mingw/mingw32
debug: adding new server URL to database 'mingw32': https://mirrors.cloud.tencent.com/msys2/mingw/mingw32
debug: registering sync database 'mingw64'
debug: database path for tree mingw64 set to /var/lib/pacman/sync/mingw64.db
debug: checking signature for /var/lib/pacman/sync/mingw64.db
debug: 1 signatures returned
debug: fingerprint: 5F944B027F7FE2091985AA2EFA11531AA0AA7F57
debug: summary: valid
debug: summary: green
debug: status: Success
debug: timestamp: 1723923967
debug: exp_timestamp: 0
debug: validity: full; reason: Success
```

Hangs after that last line.

Anyone got this working?
Anything I can do to help diagnose this further?

**Comment by phraemer** [comment] 2024-08-18 05:04
Possibly related: https://github.com/msys2/MSYS2-packages/issues/4340

**Comment by Biswa96** [comment] 2024-08-18 05:11
Yes. It is same issue. We're tracking that one. Please subscribe to that issue to get future updates.

Duplicate of https://github.com/msys2/MSYS2-packages/issues/4340

**Closed by Biswa96** 2024-08-18 05:11 UTC
