### ISSUE TITLE
in pacman -Syu showing there is nothing to do 

### ISSUE THREAD

**Issue by alip533** [msys2/msys2.github.io#181] opened 2022-01-28 05:13 UTC

**Comment by Biswa96** [comment] 2022-01-28 05:21
That means everything is up to date.

**Comment by alip533** [comment] 2022-01-28 05:23
> That means everything is up to date.

yes also this is showing and i am really tired of this issue please give me any solution about the issue

**Comment by Biswa96** [comment] 2022-01-28 05:29
There is no issue. pacman, the package manager, just shows the message if all packages are up to date.

**Comment by alip533** [comment] 2022-01-28 08:46
> There is no issue. pacman, the package manager, just shows the message if all packages are up to date.

then what i want to do for installing gcc and gdb and g++

**Comment by Biswa96** [comment] 2022-01-28 08:48
Run `pacman -S` command with the package name to install the package.

**Comment by lazka** [comment] 2022-01-28 08:48
See the tutorial on the first page of https://www.msys2.org/

**Comment by lazka** [comment] 2022-05-02 17:39
Closing as a duplicate of #192

**Closed by lazka** 2022-05-02 17:39 UTC
